### ISSUE TITLE
Initial Version Roadmap

### ISSUE THREAD

**Issue by HallM** [HallM/poc-fw2#1]
Tracking issue for roadmap. Not all items are on here for initial completion. Keeping this smaller for now to keep focus narrow and now have a huge document like the concepts doc turned into.

This has moved beyond simple POC and is actually entering true WIP.
### Components and pages
- [ ] don't crash when directories don't exist
- [x] Query parameter injection decorator
- [x] Body parameter injection decorator
- [ ] Add validation to Query and Body injection decorator
- [x] Request injection (could be from IoC)
- [x] Response injection (could be from IoC)
- [x] Page url decorator
- [ ] Action decorator
- [ ] Action method decorator
- [ ] Action url decorator
- [ ] Action automatic url generation
- [ ] Session persisting and decorator
- [ ] **How to handle logged in user??**
- [ ] **Enable/Disable streaming??**
### Page Errors
- [ ] Figure out how to handle errors in pages with the streaming API
### Config system
- [ ] The entire config system
- [ ] Get individual plugins to use the config system
### Plugins
- [x] Debate if the current style is necessary with config files. Maybe just `addPlugin(name: string)`
- [ ] Logging plugin
### IoC
- [x] Build IoC manager
- [x] IoC decorators
- [x] System-wide injectables
- [x] Per-request injectables
### Caching
- [ ] Run-once decorator to remember a value
### Component Standard Library
- [ ] Forms. This also needs some sort of Model system
- [ ] Action Links
- [ ] Navigation Links
### Helpers
- [ ] URL for page or action
### Sub-project splits
- [ ] Scope typings to sub projects
- [ ] Create package.json's for each sub project
- [ ] Split out sub projects into separate repos (or do they stay in this one a la Babel?)
### Publish to NPM
- [ ] Publish everything to NPM
